[package]
name = "guitar-gaming-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.1"
chrono = "0.4.38"
cpal = "0.15.3"
directories = "5.0.1"
pitch-detection = "0.3.0"
serde = "1.0.205"
serde_json = "1.0.122"
